
version: '3.8'

services:
  php_container:
    build:
      context: etc/infrastructure/php
      dockerfile: Dockerfile
    container_name: php_container
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - 9001:9000

  nginx_container:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - 8000:80
    volumes:
      - ./etc/infrastructure/nginx/conf.d:/etc/nginx/conf.d
      - ./apps/SymfonyClient/public/:/app/apps/SymfonyClient/public
    depends_on:
      - php_container

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    volumes:
      - ./var/rabbitmq/:/var/lib/rabbitmq/
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWD}
    ports:
      - 5672:${RABBITMQ_PORT}
      - 15672:15672
    expose:
      - ${RABBITMQ_PORT}
      - 15672
